name: "bluebell"
mode: "release"
port: 8084
version: "v0.0.1"
start_time: "2020-07-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  filename: "web_app.log"
  error_name: "web_app_error.log"
  max_size: 200
  max_age: 30
  max_backups: 7
  compress: true
  log_in_console: true
mysql:
  host: 127.0.0.1
  port: 3308
  user: "root"
  password: "asd456"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 100
